In [1]:
import numpy as np
import pandas as pd

In [2]:
abt = pd.read_parquet("Datasets/analytical_base_table.parquet")

## **Null Statistics**

In [3]:
null_counts = abt.isnull().sum()
null_percent = (abt.isnull().sum() / len(abt)) * 100

null_stats = pd.DataFrame(
    {
        "Feature": abt.columns,
        "Null Count": null_counts.values,
        "Null Percentage (%)": null_percent.round(2).values,
    }
).sort_values(by="Null Count", ascending=False)

print("Null Statistics")
null_stats

Null Statistics

                Feature  Null Count  Null Percentage (%)
0               station           0                  0.0
1                   lat           0                  0.0
2          datetime_utc           0                  0.0
3        pm25 in µg/m^3           0                  0.0
4                   lon           0                  0.0
5                  city           0                  0.0
6              province           0                  0.0
7            population           0                  0.0
8         area_in_sq.km           0                  0.0
9  density_persons/sqkm           0                  0.0

## **Numerical Feature Statistics**

In [4]:
numeric_stats = abt.describe(include=[np.number],percentiles=[0.05, 0.1, 0.25, 0.5, 0.75, 0.9, 0.95]).T
print("\nNumerical Feature Statistics")
numeric_stats

Numerical Feature Statistics

,count,mean,std,min,5%,10%,25%,50%,75%,90%,95%,max
lat,1530383.0,13.695746,1.876232,7.143752,10.694149,10.72582,14.143177,14.56746,14.636660,14.714050,15.000450,16.497420
pm25 in µg/m^3,1530383.0,181.407338,812.475555,0.000000,2.250000,4.40000,9.400000,19.98000,32.632972,69.516325,891.000000,46818.155273
lon,1530383.0,121.436620,0.992145,120.490300,120.653413,120.75050,120.986490,121.02799,121.124760,122.555171,122.558066,125.649680

## **Categorical Feature Statistics**

In [5]:
categorical_stats = abt.describe(include=["object", "category", "str"]).T
print("\nCategorical Feature Statistics")
categorical_stats

Categorical Feature Statistics

,count,unique,top,freq
station,1530383,97,"Iloilo City, Augustine Grove Subd.",83918
datetime_utc,1530383,897758,2026-09-04 01:00:00+00:00,96
city,1530383,37,Iloilo,289665
province,1530383,14,NCR,997169
population,1530383,14,"14,001,751",997169
area_in_sq.km,1530383,14,619.54,997169
density_persons/sqkm,1530383,14,"21,765",997169

## **Grouped Statistics by Province**

In [6]:
percentiles = [0.05, 0.10, 0.25, 0.50, 0.75, 0.90, 0.95]
quantile_funcs = [
    (f"p{int(p*100):02d}", (lambda q: lambda x: x.quantile(q))(p))
    for p in percentiles
]

print("\nGrouped Statistics by Province")
grouped_stats = abt.groupby("province")[["lat", "lon", "pm25 in µg/m^3"]].agg(["mean","min","max"] + quantile_funcs).T
grouped_stats

Grouped Statistics by Province

province                 Bataan       Benguet  Camarines Norte         Capiz  \
lat            mean   14.625148     16.497420        14.115700     11.430320
               min    14.436000     16.497420        14.115700     11.430320
               max    14.769440     16.497420        14.115700     11.430320
               p05    14.515000     16.497420        14.115700     11.430320
               p10    14.515000     16.497420        14.115700     11.430320
               p25    14.515000     16.497420        14.115700     11.430320
               p50    14.550700     16.497420        14.115700     11.430320
               p75    14.677590     16.497420        14.115700     11.430320
               p90    14.769440     16.497420        14.115700     11.430320
               p95    14.769440     16.497420        14.115700     11.430320
lon            mean  120.565661    120.653413       122.955100    122.926229
               min   120.490300    120.653413       122.955100    122.926229
               max   120.609000    120.653413       122.955100    122.926229
               p05   120.518200    120.653413       122.955100    122.926229
               p10   120.518200    120.653413       122.955100    122.926229
               p25   120.518200    120.653413       122.955100    122.926229
               p50   120.542780    120.653413       122.955100    122.926229
               p75   120.597500    120.653413       122.955100    122.926229
               p90   120.609000    120.653413       122.955100    122.926229
               p95   120.609000    120.653413       122.955100    122.926229
pm25 in µg/m^3 mean   10.622870    179.378833       263.195671    306.279407
               min     0.000000      0.000000         0.000000      0.000000
               max   144.970000  30952.479004      4665.000000  21693.000000
               p05     1.470000      0.400000         9.370000      3.700000
               p10     2.550000      1.668179        15.740000      7.700000
               p25     5.110000     11.600000        26.750000     24.500000
               p50     8.840000     26.500000        33.100000     35.200000
               p75    13.780000     66.492303        62.000000     63.000000
               p90    20.290000    508.038499      1087.400000    944.100000
               p95    25.970000    976.986703      1376.300000   1619.000000

province                  Cavite        Cebu  Davao del Sur  Eastern Samar  \
lat            mean    14.143177   10.326450       7.143752      10.998140
               min     14.143177   10.326450       7.143752      10.998140
               max     14.143177   10.326450       7.143752      10.998140
               p05     14.143177   10.326450       7.143752      10.998140
               p10     14.143177   10.326450       7.143752      10.998140
               p25     14.143177   10.326450       7.143752      10.998140
               p50     14.143177   10.326450       7.143752      10.998140
               p75     14.143177   10.326450       7.143752      10.998140
               p90     14.143177   10.326450       7.143752      10.998140
               p95     14.143177   10.326450       7.143752      10.998140
lon            mean   120.984941  123.978710     125.625054     125.649680
               min    120.984941  123.978710     125.625054     125.649680
               max    120.984941  123.978710     125.625054     125.649680
               p05    120.984941  123.978710     125.625054     125.649680
               p10    120.984941  123.978710     125.625054     125.649680
               p25    120.984941  123.978710     125.625054     125.649680
               p50    120.984941  123.978710     125.625054     125.649680
               p75    120.984941  123.978710     125.625054     125.649680
               p90    120.984941  123.978710     125.625054     125.649680
               p95    120.984941  123.978710     125.625054     125.649680
pm25 in µg/m^3 mean   166.848753   30.494368     171.130048       5.084836
               min      0.000000    2.260000       0.000000       0.000000
               max   5774.000000   68.620000   11396.000000     909.220000
               p05      0.000000    6.127500       0.800000       1.200000
               p10      1.000000   10.250000       2.896733       1.570000
               p25     12.000000   18.645000      13.700000       2.170000
               p50     27.800000   32.460000      30.700000       3.070000
               p75     72.000000   39.032500      62.154754       5.035000
               p90    510.000000   47.805000     575.000000       8.840000
               p95    934.800000   52.637500     945.047183      11.742000

province                   Iloilo       Laguna           NCR  \
lat            mean     10.724209    14.186235     14.586397
               min      10.694025    14.174880     14.095018
               max      10.735370    14.262660     14.750970
               p05      10.694149    14.174880     14.437546
               p10      10.694149    14.174880     14.456710
               p25      10.725820    14.174880     14.550700
               p50      10.731470    14.174880     14.586550
               p75      10.735370    14.174880     14.638420
               p90      10.735370    14.262660     14.691580
               p95      10.735370    14.262660     14.714050
lon            mean    122.548313   121.220217    121.020326
               min     122.537027   121.043380    120.892358
               max     122.580963   121.246490    121.124760
               p05     122.537027   121.043380    120.964140
               p10     122.537027   121.043380    120.971120
               p25     122.537027   121.246490    120.989880
               p50     122.546953   121.246490    121.018770
               p75     122.555171   121.246490    121.054840
               p90     122.558066   121.246490    121.077900
               p95     122.558066   121.246490    121.077900
pm25 in µg/m^3 mean    634.471834   138.544527     61.525547
               min       0.000000     0.000000      0.000000
               max   46818.155273  1038.000000  22599.760352
               p05       4.908740     0.200000      2.130000
               p10       8.068512     2.810000      4.440000
               p25      19.400000    10.800000      8.940000
               p50      30.267857    29.500000     17.670000
               p75      67.165476    53.000000     28.155445
               p90    2379.000000   678.200000     47.760000
               p95    4129.844080   823.950000     72.000000

province             Negros Occidental    Pampanga         Rizal
lat            mean          10.664885   15.044728     14.523600
               min           10.663592   15.000450     14.523600
               max           10.669405   15.193840     14.523600
               p05           10.663592   15.000450     14.523600
               p10           10.663592   15.000450     14.523600
               p25           10.663592   15.000450     14.523600
               p50           10.663592   15.024700     14.523600
               p75           10.663592   15.024700     14.523600
               p90           10.669405   15.193840     14.523600
               p95           10.669405   15.193840     14.523600
lon            mean         122.943864  120.703970    121.164525
               min          122.943439  120.638620    121.164525
               max          122.945351  120.750500    121.164525
               p05          122.943439  120.638620    121.164525
               p10          122.943439  120.638620    121.164525
               p25          122.943439  120.687230    121.164525
               p50          122.943439  120.687230    121.164525
               p75          122.943439  120.750500    121.164525
               p90          122.945351  120.750500    121.164525
               p95          122.945351  120.750500    121.164525
pm25 in µg/m^3 mean        1221.323243   69.068703    494.228374
               min            4.200000    0.000000      0.030625
               max        14366.000000  972.590000  21399.353861
               p05           21.520000    4.630000      3.061125
               p10           24.100000    6.250000      5.337821
               p25           28.000000   11.030000     13.836073
               p50           41.200000   21.050000     30.330125
               p75           67.000000   52.292500     60.528736
               p90         5443.800000  240.833000   1699.030424
               p95         7356.400000  345.434000   3021.322990

## **Unique Values for Province**

In [7]:
abt["province"].unique()

<ArrowStringArray>
[              'NCR', 'Negros Occidental',            'Bataan',
             'Rizal',           'Benguet',            'Iloilo',
            'Laguna',   'Camarines Norte',          'Pampanga',
     'Davao del Sur',              'Cebu',     'Eastern Samar',
            'Cavite',             'Capiz']
Length: 14, dtype: str